/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    vendors: Vendor;
    packages: Package;
    media: Media;
    likes: Like;
    leads: Lead;
    likesArchive: LikesArchive;
    plans: Plan;
    featured: Featured;
    todos: Todo;
    budget: Budget;
    guests: Guest;
    itinerary: Itinerary;
    chats: Chat;
    message: Message;
    misc: Misc;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {};
}
export interface User {
  id: string;
  vendor?: (string | null) | Vendor;
  packages?: (string | Package)[] | null;
  stripe_customer_id?: string | null;
  name: string;
  role: 'admin' | 'user' | 'vendor' | 'supervendor';
  userFirstLog?: boolean | null;
  vendorFirstLog?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password: string | null;
}
export interface Vendor {
  id: string;
  venduserid: string | User;
  name: string;
  category: 'venues' | 'agents' | 'bridals' | 'photovideo' | 'mua' | 'henna' | 'emceesperformers' | 'misc';
  details?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  location?: string | null;
  facebook?: string | null;
  instagram?: string | null;
  packages?: (string | Package)[] | null;
  images: {
    image: string | Media;
    id?: string | null;
  }[];
  clicks?: number | null;
  likes?: number | null;
  updatedAt: string;
  createdAt: string;
}
export interface Package {
  id: string;
  vendor: string | Vendor;
  name: string;
  services?: ('venues' | 'agents' | 'bridals' | 'photovideo' | 'mua' | 'henna' | 'emceesperformers' | 'misc')[] | null;
  packageDetails?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  pax?: number | null;
  price?: number | null;
  updatedAt: string;
  createdAt: string;
}
export interface Media {
  id: string;
  user?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
export interface Like {
  id: string;
  user: string | User;
  vendor: string | Vendor;
  updatedAt: string;
  createdAt: string;
}
export interface Lead {
  id: string;
  vendor: string | Vendor;
  name: string;
  email: string;
  contact: string;
  message?: string | null;
  source: string;
  status: string;
  priority: string;
  remarks?: string | null;
  chat?: (string | null) | Chat;
  updatedAt: string;
  createdAt: string;
}
export interface Chat {
  id: string;
  vendor: string | Vendor;
  user: string | User;
  updatedAt: string;
  createdAt: string;
}
export interface LikesArchive {
  id: string;
  user: string | User;
  vendor: string | Vendor;
  updatedAt: string;
  createdAt: string;
}
export interface Plan {
  id: string;
  user: (string | User)[];
  totalVer?: number | null;
  brideName?: string | null;
  groomName?: string | null;
  weddingDate?: string | null;
  venue?: (string | null) | Vendor;
  agent?: (string | null) | Vendor;
  bridal?: (string | null) | Vendor;
  photovideo?: (string | null) | Vendor;
  mua?: (string | null) | Vendor;
  henna?: (string | null) | Vendor;
  emceesperformers?: (string | null) | Vendor;
  misc?: (string | null) | Vendor;
  packages?: (string | Package)[] | null;
  updatedAt: string;
  createdAt: string;
}
export interface Featured {
  id: string;
  top1Venue?: (string | null) | Vendor;
  top4Venues?:
    | {
        vendor?: (string | null) | Vendor;
        id?: string | null;
      }[]
    | null;
  top1Agent?: (string | null) | Vendor;
  top4Agents?:
    | {
        vendor?: (string | null) | Vendor;
        id?: string | null;
      }[]
    | null;
  top1Bridal?: (string | null) | Vendor;
  top4Bridals?:
    | {
        vendor?: (string | null) | Vendor;
        id?: string | null;
      }[]
    | null;
  top1Photovideo?: (string | null) | Vendor;
  top4Photovideo?:
    | {
        vendor?: (string | null) | Vendor;
        id?: string | null;
      }[]
    | null;
  top1Mua?: (string | null) | Vendor;
  top4Mua?:
    | {
        vendor?: (string | null) | Vendor;
        id?: string | null;
      }[]
    | null;
  top1Henna?: (string | null) | Vendor;
  top4Henna?:
    | {
        vendor?: (string | null) | Vendor;
        id?: string | null;
      }[]
    | null;
  top1Emcee?: (string | null) | Vendor;
  top4Emcees?:
    | {
        vendor?: (string | null) | Vendor;
        id?: string | null;
      }[]
    | null;
  top1Misc?: (string | null) | Vendor;
  top4Misc?:
    | {
        vendor?: (string | null) | Vendor;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
export interface Todo {
  id: string;
  plan: string | Plan;
  todo: string;
  remarks?: string | null;
  date: string;
  done: boolean;
  updatedAt: string;
  createdAt: string;
}
export interface Budget {
  id: string;
  plan: string | Plan;
  ver?: number | null;
  for: string;
  cat: string;
  details: string;
  plannedCost?: number | null;
  actualCost?: number | null;
  amountPaid?: number | null;
  updatedAt: string;
  createdAt: string;
}
export interface Guest {
  id: string;
  plan: string | Plan;
  group: string;
  name: string;
  pax: number;
  attendance: string;
  sent: boolean;
  updatedAt: string;
  createdAt: string;
}
export interface Itinerary {
  id: string;
  plan: string | Plan;
  date: string;
  time: number;
  location: string;
  event: string;
  involved: string;
  details: string;
  updatedAt: string;
  createdAt: string;
}
export interface Message {
  id: string;
  chat: string | Chat;
  from: string;
  message: string;
  read: boolean;
  updatedAt: string;
  createdAt: string;
}
export interface Misc {
  id: string;
  berkat?: (string | Vendor)[] | null;
  decor?: (string | Vendor)[] | null;
  dulang?: (string | Vendor)[] | null;
  liveStation?: (string | Vendor)[] | null;
  cake?: (string | Vendor)[] | null;
  catering?: (string | Vendor)[] | null;
  pakandam?: (string | Vendor)[] | null;
  updatedAt: string;
  createdAt: string;
}
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}