/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    vendors: Vendor;
    packages: Package;
    media: Media;
    likes: Like;
    leads: Lead;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {};
}
export interface User {
  id: string;
  vendor?: (string | null) | Vendor;
  packages?: (string | Package)[] | null;
  role: 'admin' | 'user' | 'vendor' | 'supervendor' | 'platinum' | 'elite';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password: string | null;
}
export interface Vendor {
  id: string;
  venduserid: string | User;
  name: string;
  category:
    | 'venues'
    | 'agents'
    | 'bridals'
    | 'photovideo'
    | 'catering'
    | 'decor'
    | 'henna'
    | 'mua'
    | 'emcees'
    | 'honeymoon'
    | 'misc';
  details?: string | null;
  location?: string | null;
  packages?: (string | Package)[] | null;
  images?:
    | {
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
export interface Package {
  id: string;
  user?: (string | null) | User;
  name: string;
  services?:
    | (
        | 'venues'
        | 'agents'
        | 'bridals'
        | 'photovideo'
        | 'catering'
        | 'decor'
        | 'henna'
        | 'mua'
        | 'emcees'
        | 'honeymoon'
        | 'misc'
      )[]
    | null;
  packageDetails?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  pax?: number | null;
  price?: number | null;
  updatedAt: string;
  createdAt: string;
}
export interface Media {
  id: string;
  user?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
export interface Like {
  id: string;
  user: string | User;
  vendor: string | Vendor;
  updatedAt: string;
  createdAt: string;
}
export interface Lead {
  id: string;
  vendor: string | Vendor;
  name: string;
  email: string;
  contact: string;
  message?: string | null;
  source: string;
  status: 'not contacted' | 'warm' | 'hot' | 'cold' | 'lnr' | 'not interested' | 'contract signed';
  priority: 'low' | 'medium' | 'high';
  remarks?: string | null;
  updatedAt: string;
  createdAt: string;
}
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}