/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    vendors: Vendor;
    packages: Package;
    media: Media;
    likes: Like;
    leads: Lead;
    likesArchive: LikesArchive;
    plans: Plan;
    featured: Featured;
    todos: Todo;
    budget: Budget;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {};
}
export interface User {
  id: string;
  vendor?: (string | null) | Vendor;
  packages?: (string | Package)[] | null;
  stripe_customer_id?: string | null;
  role: 'admin' | 'user' | 'vendor' | 'supervendor' | 'platinum' | 'elite';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password: string | null;
}
export interface Vendor {
  id: string;
  venduserid: string | User;
  name: string;
  category:
    | 'venues'
    | 'agents'
    | 'bridals'
    | 'photovideo'
    | 'catering'
    | 'decor'
    | 'henna'
    | 'mua'
    | 'emcees'
    | 'honeymoon'
    | 'misc';
  details?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  location?: string | null;
  facebook?: string | null;
  instagram?: string | null;
  packages?: (string | Package)[] | null;
  images?:
    | {
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
export interface Package {
  id: string;
  vendor: string | Vendor;
  name: string;
  services?:
    | (
        | 'venues'
        | 'agents'
        | 'bridals'
        | 'photovideo'
        | 'catering'
        | 'decor'
        | 'henna'
        | 'mua'
        | 'emcees'
        | 'honeymoon'
        | 'misc'
      )[]
    | null;
  packageDetails?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  pax?: number | null;
  price?: number | null;
  updatedAt: string;
  createdAt: string;
}
export interface Media {
  id: string;
  user?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
export interface Like {
  id: string;
  user: string | User;
  vendor: string | Vendor;
  updatedAt: string;
  createdAt: string;
}
export interface Lead {
  id: string;
  vendor: string | Vendor;
  name: string;
  email: string;
  contact: string;
  message?: string | null;
  source: string;
  status: 'not contacted' | 'warm' | 'hot' | 'cold' | 'lnr' | 'not interested' | 'contract signed';
  priority: 'low' | 'medium' | 'high';
  remarks?: string | null;
  updatedAt: string;
  createdAt: string;
}
export interface LikesArchive {
  id: string;
  user: string | User;
  vendor: string | Vendor;
  updatedAt: string;
  createdAt: string;
}
export interface Plan {
  id: string;
  user: (string | User)[];
  brideName?: string | null;
  groomName?: string | null;
  weddingDate?: string | null;
  venue?: (string | null) | Vendor;
  agent?: (string | null) | Vendor;
  bridal?: (string | null) | Vendor;
  photovideo?: (string | null) | Vendor;
  catering?: (string | null) | Vendor;
  decor?: (string | null) | Vendor;
  henna?: (string | null) | Vendor;
  mua?: (string | null) | Vendor;
  emcee?: (string | null) | Vendor;
  honeymoon?: (string | null) | Vendor;
  misc?: (string | null) | Vendor;
  updatedAt: string;
  createdAt: string;
}
export interface Featured {
  id: string;
  top1Venue?: (string | null) | Vendor;
  top4Venues?:
    | {
        vendor?: (string | null) | Vendor;
        id?: string | null;
      }[]
    | null;
  top1Agent?: (string | null) | Vendor;
  top4Agents?:
    | {
        vendor?: (string | null) | Vendor;
        id?: string | null;
      }[]
    | null;
  top1Bridal?: (string | null) | Vendor;
  top4Bridals?:
    | {
        vendor?: (string | null) | Vendor;
        id?: string | null;
      }[]
    | null;
  top1Photovideo?: (string | null) | Vendor;
  top4Photovideo?:
    | {
        vendor?: (string | null) | Vendor;
        id?: string | null;
      }[]
    | null;
  top1Catering?: (string | null) | Vendor;
  top4Catering?:
    | {
        vendor?: (string | null) | Vendor;
        id?: string | null;
      }[]
    | null;
  top1Decor?: (string | null) | Vendor;
  top4Decor?:
    | {
        vendor?: (string | null) | Vendor;
        id?: string | null;
      }[]
    | null;
  top1Henna?: (string | null) | Vendor;
  top4Henna?:
    | {
        vendor?: (string | null) | Vendor;
        id?: string | null;
      }[]
    | null;
  top1Mua?: (string | null) | Vendor;
  top4Mua?:
    | {
        vendor?: (string | null) | Vendor;
        id?: string | null;
      }[]
    | null;
  top1Emcee?: (string | null) | Vendor;
  top4Emcees?:
    | {
        vendor?: (string | null) | Vendor;
        id?: string | null;
      }[]
    | null;
  top1Honeymoon?: (string | null) | Vendor;
  top4Honeymoon?:
    | {
        vendor?: (string | null) | Vendor;
        id?: string | null;
      }[]
    | null;
  top1Misc?: (string | null) | Vendor;
  top4Misc?:
    | {
        vendor?: (string | null) | Vendor;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
export interface Todo {
  id: string;
  plan: string | Plan;
  todo: string;
  remarks?: string | null;
  date: string;
  done: boolean;
  updatedAt: string;
  createdAt: string;
}
export interface Budget {
  id: string;
  plan: string | Plan;
  for: string;
  cat: string;
  details: string;
  plannedCost?: number | null;
  actualCost?: number | null;
  amountPaid?: number | null;
  updatedAt: string;
  createdAt: string;
}
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}